name: Generate Pacman & Snake Animations

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # ---- Pacman ----
      - name: Generate pacman-contribution-graph.svg (light)
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # ---- Snake ----
      - name: Generate snake.svg (light)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Generate snake-dark.svg (dark)
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          palette: github-dark
          outputs: dist/snake-dark.svg

      # ---- Push all to output branch ----
      - name: Push animations to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
